version: '2'

services:
  redis:
    image: 'redis:3.2'
#    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - 'redis:/data'
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

#  wrapperapp:
#    build: ./WRAPPER
 #   command: > 
  #  volumes:
   #   - '.:/app'
  #  ports:
  #    - '9603:9603'

#  intermediateapp:
 #   build: ./Intermediate
#    command: >
#    volumes:
#      - '.:/app'
 #   ports:
  #    - '9604:9604'
      
  rootapp: 
    build: .
    command: "python app_model5.py" 
    volumes:
      - '.:/app'
    ports:
      - '9605:9605'

  celery:
    build: .
    environment:
      - C_FORCE_ROOT=true
    command: "celery worker -A app_model5.celery --loglevel=info"
    volumes:
      - '.:/app'

volumes:
  redis:
